#include <vector>
#include <array>
#include <random>
#include <algorithm>
#include <stdexcept>
#include <memory>
#include <string>
#include <functional>
#include <thread>

#include <QApplication>
#include <QMainWindow>
#include <QWidget>
#include <QStackedWidget>
#include <QVBoxLayout>
#include <QHBoxLayout>
#include <QGridLayout>
#include <QPushButton>
#include <QLabel>
#include <QFrame>
#include <QMessageBox>
#include <QVector>
#include <QDialog>
#include <QLineEdit>
#include <QSpinBox>
